version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-service
    image: ewm-stats-service
    container_name: stats-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
      - stats-client
    environment:
      - DB_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  stats-client:
#    build: ewm-stats-service/stats-service-client
#    image: ewm-stats-service-client
#    container_name: stats-client
#    ports:
#      - "9090:9090"
