version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-service
    image: ewm-stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main-service/
    image: ewm-main-service-image
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - EWM_DB_URL=jdbc:postgresql://ewm-db:5433/ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14.3-alpine
    container_name: ewm-db
    ports:
      - "6542:5433"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
